In [8]:
import pandas as pd

In [ ]:
# Imprtando dados de 2015_01

df_2015_01 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2015-01.csv", sep=';')

In [19]:
df_2015_01.info()

<class 'pandas.DataFrame'>
RangeIndex: 696774 entries, 0 to 696773
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     696774 non-null  str
 1   Estado - Sigla     696774 non-null  str
 2   Municipio          696774 non-null  str
 3   Revenda            696774 non-null  str
 4   CNPJ da Revenda    696774 non-null  str
 5   Nome da Rua        696774 non-null  str
 6   Numero Rua         696341 non-null  str
 7   Complemento        181073 non-null  str
 8   Bairro             694242 non-null  str
 9   Cep                696774 non-null  str
 10  Produto            696774 non-null  str
 11  Data da Coleta     696774 non-null  str
 12  Valor de Venda     696774 non-null  str
 13  Valor de Compra    266617 non-null  str
 14  Unidade de Medida  696774 non-null  str
 15  Bandeira           696774 non-null  str
dtypes: str(16)
memory usage: 85.1 MB

In [18]:
df_2015_01.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,GASOLINA,01/01/2015,"3,44",NaN,R$ / litro,DNP
1,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,ETANOL,01/01/2015,3,NaN,R$ / litro,DNP
2,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,DIESEL,01/01/2015,"3,1",NaN,R$ / litro,DNP
3,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,DIESEL S10,01/01/2015,"3,2",NaN,R$ / litro,DNP
4,N,AC,SENADOR GUIOMARD,AUTO POSTO QUINARI LTDA,10.209.732/0001-40,AVENIDA CASTELO BRANCO,2709,NaN,CENTRO,69925-000,GASOLINA,01/01/2015,"3,44","2,784",R$ / litro,SABBÁ

In [ ]:
# Imprtando dados de 2015_02

df_2015_02 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2015-02.csv", sep=';')

In [20]:
df_2015_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 410974 entries, 0 to 410973
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     410974 non-null  str
 1   Estado - Sigla     410974 non-null  str
 2   Municipio          410974 non-null  str
 3   Revenda            410974 non-null  str
 4   CNPJ da Revenda    410974 non-null  str
 5   Nome da Rua        410974 non-null  str
 6   Numero Rua         410697 non-null  str
 7   Complemento        104189 non-null  str
 8   Bairro             409723 non-null  str
 9   Cep                410974 non-null  str
 10  Produto            410974 non-null  str
 11  Data da Coleta     410974 non-null  str
 12  Valor de Venda     410974 non-null  str
 13  Valor de Compra    164426 non-null  str
 14  Unidade de Medida  410974 non-null  str
 15  Bandeira           410974 non-null  str
dtypes: str(16)
memory usage: 50.2 MB

In [23]:
df_2015_02.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,BA,SALVADOR,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0015-08,RUA EDISTIO PONDE,474,NaN,STIEP,41770-395,GASOLINA,01/07/2015,"3,59","3,0296",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,NE,BA,SALVADOR,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0015-08,RUA EDISTIO PONDE,474,NaN,STIEP,41770-395,ETANOL,01/07/2015,"2,599","2,0941",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,NE,BA,SALVADOR,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0015-08,RUA EDISTIO PONDE,474,NaN,STIEP,41770-395,DIESEL S10,01/07/2015,"2,89","2,687",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,NE,BA,SALVADOR,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0015-08,RUA EDISTIO PONDE,474,NaN,STIEP,41770-395,GNV,01/07/2015,"2,19","1,44",R$ / m³,PETROBRAS DISTRIBUIDORA S.A.
4,S,PR,PATO BRANCO,SANTOS & MERLO LTDA.,79.854.667/0001-01,RUA TOCANTINS,2535,NaN,CENTRO,85501-010,GASOLINA,01/07/2015,"3,39",NaN,R$ / litro,MAZP DISTRIBUIDORA

In [ ]:
# Importando dados de 2016/01
df_2016_01 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2016-01.csv", sep=';')

In [25]:
df_2016_01.info()

<class 'pandas.DataFrame'>
RangeIndex: 486897 entries, 0 to 486896
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     486897 non-null  str
 1   Estado - Sigla     486897 non-null  str
 2   Municipio          486897 non-null  str
 3   Revenda            486897 non-null  str
 4   CNPJ da Revenda    486897 non-null  str
 5   Nome da Rua        486897 non-null  str
 6   Numero Rua         486619 non-null  str
 7   Complemento        124413 non-null  str
 8   Bairro             485102 non-null  str
 9   Cep                486897 non-null  str
 10  Produto            486897 non-null  str
 11  Data da Coleta     486897 non-null  str
 12  Valor de Venda     486897 non-null  str
 13  Valor de Compra    191504 non-null  str
 14  Unidade de Medida  486897 non-null  str
 15  Bandeira           486897 non-null  str
dtypes: str(16)
memory usage: 59.4 MB

In [26]:
df_2016_01.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,GASOLINA,06/01/2016,"3,31",NaN,R$ / litro,BRANCA
1,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,ETANOL,06/01/2016,"2,31",NaN,R$ / litro,BRANCA
2,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,DIESEL,06/01/2016,"2,65",NaN,R$ / litro,BRANCA
3,NE,BA,ITABUNA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA,00.231.792/0001-05,RODOVIA BR 101,SN,KM 503 5,MANOEL LEAO,45601-402,GASOLINA,04/01/2016,"3,69",NaN,R$ / litro,BRANCA
4,NE,BA,ITABUNA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA,00.231.792/0001-05,RODOVIA BR 101,SN,KM 503 5,MANOEL LEAO,45601-402,DIESEL,04/01/2016,"2,97",NaN,R$ / litro,BRANCA

In [ ]:
# Importando