In [10]:
# Importando as bibliotecas

import pandas as pd 
import numpy as np
import os
from datetime import datetime, date
from google.cloud import bigquery
from dotenv import load_dotenv
import pyarrow


# Carregando variáveis de ambiente
load_dotenv()

True

In [2]:
# Imprtando dados de 2016_01

df_2016_01 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2016-01.csv", sep=';')

In [3]:
df_2016_01.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,GASOLINA,06/01/2016,"3,31",NaN,R$ / litro,BRANCA
1,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,ETANOL,06/01/2016,"2,31",NaN,R$ / litro,BRANCA
2,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,DIESEL,06/01/2016,"2,65",NaN,R$ / litro,BRANCA
3,NE,BA,ITABUNA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA,00.231.792/0001-05,RODOVIA BR 101,SN,KM 503 5,MANOEL LEAO,45601-402,GASOLINA,04/01/2016,"3,69",NaN,R$ / litro,BRANCA
4,NE,BA,ITABUNA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA,00.231.792/0001-05,RODOVIA BR 101,SN,KM 503 5,MANOEL LEAO,45601-402,DIESEL,04/01/2016,"2,97",NaN,R$ / litro,BRANCA

In [4]:
df_2016_02 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2016-02.csv", sep=';')

In [5]:
df_2016_02.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,GASOLINA,04/07/2016,"3,29",NaN,R$ / litro,BRANCA
1,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,ETANOL,04/07/2016,"2,04",NaN,R$ / litro,BRANCA
2,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,DIESEL,04/07/2016,"2,79",NaN,R$ / litro,BRANCA
3,S,RS,CANOAS,METROPOLITANO COMERCIO DE COMBUSTIVEIS LTDA,88.587.589/0001-17,AVENIDA GUILHERME SCHELL,6340,NaN,CENTRO,92310-000,GASOLINA,05/07/2016,"3,65","3,23",R$ / litro,BRANCA
4,S,RS,CANOAS,METROPOLITANO COMERCIO DE COMBUSTIVEIS LTDA,88.587.589/0001-17,AVENIDA GUILHERME SCHELL,6340,NaN,CENTRO,92310-000,ETANOL,05/07/2016,"3,15","2,6448",R$ / litro,BRANCA

In [6]:
df_2016 = pd.concat((df_2016_01, df_2016_02))

In [7]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 975857 entries, 0 to 488959
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     975857 non-null  object
 1   Estado - Sigla     975857 non-null  object
 2   Municipio          975857 non-null  object
 3   Revenda            975857 non-null  object
 4   CNPJ da Revenda    975857 non-null  object
 5   Nome da Rua        975857 non-null  object
 6   Numero Rua         975286 non-null  object
 7   Complemento        250979 non-null  object
 8   Bairro             972105 non-null  object
 9   Cep                975857 non-null  object
 10  Produto            975857 non-null  object
 11  Data da Coleta     975857 non-null  object
 12  Valor de Venda     975857 non-null  object
 13  Valor de Compra    419788 non-null  object
 14  Unidade de Medida  975857 non-null  object
 15  Bandeira           975857 non-null  object
dtypes: object(16)
memory usage: 126.6+ MB

In [ ]:
df_2016_pe = df_2016[df_2016["Estado - Sigla"] == "PE"]

In [9]:
df_2016_pe.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
3905,NE,PE,ABREU E LIMA,COSTA DOURADA COMBUSTÍVEIS E LUBRIFICANTES LTDA.,06.053.230/0002-86,AVENIDA D,S/N,NaN,CAETES,53540-000,GASOLINA,04/01/2016,"3,599","3,236",R$ / litro,FEDERAL
3906,NE,PE,ABREU E LIMA,COSTA DOURADA COMBUSTÍVEIS E LUBRIFICANTES LTDA.,06.053.230/0002-86,AVENIDA D,S/N,NaN,CAETES,53540-000,ETANOL,04/01/2016,"2,799","2,472",R$ / litro,FEDERAL
3907,NE,PE,ABREU E LIMA,COSTA DOURADA COMBUSTÍVEIS E LUBRIFICANTES LTDA.,06.053.230/0002-86,AVENIDA D,S/N,NaN,CAETES,53540-000,DIESEL S10,04/01/2016,"2,999","2,728",R$ / litro,FEDERAL
3908,NE,PE,ABREU E LIMA,AUTO POSTO CABRAL COMBUSTIVEIS LTDA,08.131.708/0001-93,AVENIDA DUQUE DE CAXIAS,1162,NaN,BOA ESPERANCA,53580-020,GASOLINA,04/01/2016,"3,79","3,2358",R$ / litro,BRANCA
3909,NE,PE,ABREU E LIMA,AUTO POSTO CABRAL COMBUSTIVEIS LTDA,08.131.708/0001-93,AVENIDA DUQUE DE CAXIAS,1162,NaN,BOA ESPERANCA,53580-020,ETANOL,04/01/2016,"2,69","2,4696",R$ / litro,BRANCA

In [ ]:
# Configurando credenciais

# Caminho do arquivo de credenciais GCP
credencial = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# Identificador do projeto no GCP
project_id = os.getenv("PROJECT_ID")

# Tabela Staging no BigQuery
table_id = os.getenv("STG_2016")

# Inicialização do cliente BigQuery

# Define a variavel de ambiente
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credencial

# Cria o cliente Bigquery ao projeto configurado
client = bigquery.Client(project=project_id)