In [1]:
# Importando as bibliotecas

import pandas as pd 
import numpy as np
import os
from datetime import datetime, date
from google.cloud import bigquery
from dotenv import load_dotenv
import pyarrow


# Carregando variáveis de ambiente
load_dotenv()

True

In [2]:
df_2017_01 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2017-01.csv", sep=';')

In [3]:
df_2017_01.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,GASOLINA,03/01/2017,"3,699","3,1874",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,ETANOL,03/01/2017,"2,899","2,4963",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,DIESEL,03/01/2017,"2,959","2,5284",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,DIESEL S10,03/01/2017,"3,079","2,6658",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
4,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,GNV,03/01/2017,"2,099",NaN,R$ / m³,PETROBRAS DISTRIBUIDORA S.A.

In [4]:
df_2017_02 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2017-02.csv", sep=';')

In [5]:
df_2017_02.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,GASOLINA,06/07/2017,"3,11",NaN,R$ / litro,BRANCA
1,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,ETANOL,06/07/2017,"2,02",NaN,R$ / litro,BRANCA
2,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,DIESEL S10,06/07/2017,"2,86",NaN,R$ / litro,BRANCA
3,NE,BA,ITABUNA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA,00.231.792/0001-05,RODOVIA BR 101,SN,KM 503 5,MANOEL LEAO,45601-402,GASOLINA,05/07/2017,"3,599",NaN,R$ / litro,BRANCA
4,NE,BA,ITABUNA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA,00.231.792/0001-05,RODOVIA BR 101,SN,KM 503 5,MANOEL LEAO,45601-402,DIESEL,05/07/2017,"2,87",NaN,R$ / litro,BRANCA

In [6]:
df_2017 = pd.concat((df_2017_01,df_2017_02))

In [7]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 788606 entries, 0 to 300946
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     788606 non-null  object
 1   Estado - Sigla     788606 non-null  object
 2   Municipio          788606 non-null  object
 3   Revenda            788606 non-null  object
 4   CNPJ da Revenda    788606 non-null  object
 5   Nome da Rua        788606 non-null  object
 6   Numero Rua         788199 non-null  object
 7   Complemento        206065 non-null  object
 8   Bairro             785888 non-null  object
 9   Cep                788606 non-null  object
 10  Produto            788606 non-null  object
 11  Data da Coleta     788606 non-null  object
 12  Valor de Venda     788606 non-null  object
 13  Valor de Compra    355765 non-null  object
 14  Unidade de Medida  788606 non-null  object
 15  Bandeira           788606 non-null  object
dtypes: object(16)
memory usage: 102.3+ MB

In [8]:
df_2017_pe = df_2017[df_2017["Estado - Sigla"] == "PE"]

In [9]:
df_2017_pe.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
3591,NE,PE,ABREU E LIMA,COSTA DOURADA COMBUSTÍVEIS E LUBRIFICANTES LTDA.,06.053.230/0002-86,AVENIDA D,S/N,NaN,CAETES,53540-000,GASOLINA,02/01/2017,"3,399",NaN,R$ / litro,FEDERAL
3592,NE,PE,ABREU E LIMA,COSTA DOURADA COMBUSTÍVEIS E LUBRIFICANTES LTDA.,06.053.230/0002-86,AVENIDA D,S/N,NaN,CAETES,53540-000,ETANOL,02/01/2017,"2,799",NaN,R$ / litro,FEDERAL
3593,NE,PE,ABREU E LIMA,COSTA DOURADA COMBUSTÍVEIS E LUBRIFICANTES LTDA.,06.053.230/0002-86,AVENIDA D,S/N,NaN,CAETES,53540-000,DIESEL S10,02/01/2017,"2,859",NaN,R$ / litro,FEDERAL
3594,NE,PE,ABREU E LIMA,AUTO POSTO CABRAL COMBUSTIVEIS LTDA,08.131.708/0001-93,AVENIDA DUQUE DE CAXIAS,1162,NaN,BOA ESPERANCA,53580-020,GASOLINA,02/01/2017,"3,36","3,005",R$ / litro,FEDERAL
3595,NE,PE,ABREU E LIMA,AUTO POSTO CABRAL COMBUSTIVEIS LTDA,08.131.708/0001-93,AVENIDA DUQUE DE CAXIAS,1162,NaN,BOA ESPERANCA,53580-020,ETANOL,02/01/2017,"2,799","2,4095",R$ / litro,FEDERAL

In [ ]:
# Configurando credenciais

# Caminho do arquivo de credenciais GCP
credencial = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# Identificador do projeto no GCP
project_id = os.getenv("PROJECT_ID")

# Tabela Bronze no BigQuery
table_id = os.getenv("BRONZE_2017")

# Inicialização do cliente BigQuery

# Define a variavel de ambiente
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credencial

# Cria o cliente Bigquery ao projeto configurado
client = bigquery.Client(project=project_id)

In [11]:
# Criação e carga da tabela de BRONZE

# Configuração do job de carga no BigQuery
# WRITE_TRUNCATE garante que a tabela Bronze seja sempre sobrescrita,
# mantendo apenas o retrato mais recente dos dados de origem
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE"
)

# Envia o DataFrame para o BigQuery,
# criando a tabela automaticamente caso ainda não exista
job = client.load_table_from_dataframe(
    df_2017_pe,
    table_id,
    job_config=job_config
)

# Aguarda a finalização do job para garantir consistência da carga
job.result()

# Confirmação visual de sucesso da operação
print("✅ Tabela Bronze criada e dados carregados com sucesso")

/home/danielpedro/anaconda3/envs/combustivel_projeto/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Tabela Bronze criada e dados carregados com sucesso