In [1]:
# Importando as bibliotecas

import pandas as pd 
import numpy as np
import os
from datetime import datetime, date
from google.cloud import bigquery
from dotenv import load_dotenv
import pyarrow


# Carregando variáveis de ambiente
load_dotenv()

True

In [2]:
# Imprtando dados de 2015_01

df_2015_01 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2015-01.csv", sep=';')

In [3]:
# Imprtando dados de 2015_02

df_2015_02 = pd.read_csv("/home/danielpedro/Engenharia de Dados/combustivel_preco2015_2025/dataset/ca-2015-02.csv", sep=';')

In [4]:
# Unindo os dois df
df_2015 =  pd.concat((df_2015_01, df_2015_02))

In [5]:
df_2015.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,GASOLINA,01/01/2015,"3,44",NaN,R$ / litro,DNP
1,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,ETANOL,01/01/2015,3,NaN,R$ / litro,DNP
2,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,DIESEL,01/01/2015,"3,1",NaN,R$ / litro,DNP
3,N,AC,SENADOR GUIOMARD,AUTO POSTO SANTA RITA LTDA.,07.600.665/0001-85,AVENIDA CASTELO BRANCO,122,NaN,TRIUNFO,69925-000,DIESEL S10,01/01/2015,"3,2",NaN,R$ / litro,DNP
4,N,AC,SENADOR GUIOMARD,AUTO POSTO QUINARI LTDA,10.209.732/0001-40,AVENIDA CASTELO BRANCO,2709,NaN,CENTRO,69925-000,GASOLINA,01/01/2015,"3,44","2,784",R$ / litro,SABBÁ

In [6]:
df_2015.tail()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
410969,SE,MG,SETE LAGOAS,POSTO PETROLAGOS LTDA,19.863.856/0001-19,RODOVIA MG-424,0,KM: 04;,ESMERALDAS,35702-098,DIESEL,28/12/2015,"2,799","2,6316",R$ / litro,ALESAT
410970,SE,MG,SETE LAGOAS,POSTO PETROLAGOS LTDA,19.863.856/0001-19,RODOVIA MG-424,0,KM: 04;,ESMERALDAS,35702-098,DIESEL S10,28/12/2015,"2,999","2,7802",R$ / litro,ALESAT
410971,N,AC,RIO BRANCO,POSTO ALTO ALEGRE LTDA,20.420.950/0001-82,RODOVIA AC 10,1321,NaN,ALTO ALEGRE,69914-720,GASOLINA,30/12/2015,"3,92","3,5053",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
410972,N,AC,RIO BRANCO,POSTO ALTO ALEGRE LTDA,20.420.950/0001-82,RODOVIA AC 10,1321,NaN,ALTO ALEGRE,69914-720,ETANOL,30/12/2015,"3,18","2,5234",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
410973,N,AC,RIO BRANCO,POSTO ALTO ALEGRE LTDA,20.420.950/0001-82,RODOVIA AC 10,1321,NaN,ALTO ALEGRE,69914-720,DIESEL,30/12/2015,"3,48","3,1009",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.

In [7]:
df_2015_pe = df_2015[df_2015["Estado - Sigla"] == "PE"]

In [8]:
df_2015_pe

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
270,NE,PE,LAJEDO,JM COMBUSTIVEIS LTDA.,09.273.777/0001-02,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK,S/N,NaN,CENTRO,55385-000,GASOLINA,01/01/2015,"2,989","2,527",R$ / litro,BRANCA
271,NE,PE,LAJEDO,JM COMBUSTIVEIS LTDA.,09.273.777/0001-02,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK,S/N,NaN,CENTRO,55385-000,ETANOL,01/01/2015,"2,289",NaN,R$ / litro,BRANCA
272,NE,PE,LAJEDO,JM COMBUSTIVEIS LTDA.,09.273.777/0001-02,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK,S/N,NaN,CENTRO,55385-000,DIESEL,01/01/2015,"2,489","2,29",R$ / litro,BRANCA
273,NE,PE,LAJEDO,I. DE MEDEIROS SALES COMBUSTIVEIS,07.620.681/0001-30,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEC,990,NaN,CENTRO,55385-000,GASOLINA,01/01/2015,"2,989",NaN,R$ / litro,BRANCA
274,NE,PE,LAJEDO,I. DE MEDEIROS SALES COMBUSTIVEIS,07.620.681/0001-30,AVENIDA PRESIDENTE JUSCELINO KUBITSCHEC,990,NaN,CENTRO,55385-000,ETANOL,01/01/2015,"2,359",NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410927,NE,PE,JABOATAO DOS GUARARAPES,ROCHA & CARNEIRO COMBUSTIVEIS E SERVICOS LTDA,18.311.003/0001-01,RUA BARAO DE MORENO,7,NaN,VILA RICA,54100-680,DIESEL S10,29/12/2015,"3,049",NaN,R$ / litro,SETTA DISTRIBUIDORA
410963,NE,PE,LAJEDO,OASIS COMBUSTIVEIS LTDA,17.322.859/0001-10,RUA PERPETUO SOCORRO,149,NaN,CENTRO,55385-000,GASOLINA,29/12/2015,"3,599",NaN,R$ / litro,IPIRANGA
410964,NE,PE,LAJEDO,OASIS COMBUSTIVEIS LTDA,17.322.859/0001-10,RUA PERPETUO SOCORRO,149,NaN,CENTRO,55385-000,ETANOL,29/12/2015,"2,999",NaN,R$ / litro,IPIRANGA
410965,NE,PE,LAJEDO,OASIS COMBUSTIVEIS LTDA,17.322.859/0001-10,RUA PERPETUO SOCORRO,149,NaN,CENTRO,55385-000,DIESEL,29/12/2015,"2,899",NaN,R$ / litro,IPIRANGA
410966,NE,PE,LAJEDO,OASIS COMBUSTIVEIS LTDA,17.322.859/0001-10,RUA PERPETUO SOCORRO,149,NaN,CENTRO,55385-000,DIESEL S10,29/12/2015,"2,999",NaN,R$ / litro,IPIRANGA

In [ ]:
# Configurando credenciais

# Caminho do arquivo de credenciais GCP
credencial = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# Identificador do projeto no GCP
project_id = os.getenv("PROJECT_ID")

# Tabela Bronze no BigQuery
table_id = os.getenv("BRONZE_2015")

# Inicialização do cliente BigQuery

# Define a variavel de ambiente
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credencial

# Cria o cliente Bigquery ao projeto configurado
client = bigquery.Client(project=project_id)

In [10]:
# Criação e carga da Tabela BRONZE

# Configuração do job de carga no BigQuery
# WRITE_TRUNCATE garante que a tabela Bronze seja sempre sobrescrita,
# mantendo apenas o retrato mais recente dos dados de origem
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE"
)

# Envia o DataFrame para o BigQuery,
# criando a tabela automaticamente caso ainda não exista
job = client.load_table_from_dataframe(
    df_2015_pe,
    table_id,
    job_config=job_config
)

# Aguarda a finalização do job para garantir consistência da carga
job.result()

# Confirmação visual de sucesso da operação
print("✅ Tabela Bronze criada e dados carregados com sucesso")

/home/danielpedro/anaconda3/envs/combustivel_projeto/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✅ Tabela Bronze criada e dados carregados com sucesso